service: t2e-food
image: markyiptw/t2e-food

servers:
  web:
    - 43.199.193.158
  queue:
    hosts:
      - 43.199.193.158
    cmd: "php /var/www/html/artisan queue:work"
    options:
      health-cmd: "healthcheck-queue"
  task:
    hosts:
      - 43.199.193.158
    cmd: "php /var/www/html/artisan schedule:work"
    options:
      health-cmd: "healthcheck-schedule"

builder:
  arch:
    - arm64
  secrets: # not a env -> secret, so can't use alias?
    - VITE_POSTHOG_API_KEY # probably need to fix Dockerfile as well

proxy:
  ssl: true
  host: www.t2e.food
  # default is 80
  # but our image listens to 8080
  app_port: 8080
  response_timeout: 120

registry:
  server: localhost:5555

env:
  clear:
    DB_CONNECTION: pgsql
    # hostname inside docker = ${service}-${accessory}
    DB_HOST: t2e-food-db
    DB_USERNAME: postgres
    DB_DATABASE: postgres
    AUTORUN_ENABLED: true
    LOG_CHANNEL: stdout
    PHP_OPCACHE_ENABLE: "1"
  secret:
    - APP_KEY
    - DB_PASSWORD
    - POSTHOG_API_KEY

ssh:
  user: ec2-user

volumes:
  - "app_storage:/var/www/html/storage/app"

asset_path: /var/www/html/public/build/assets

accessories:
  db:
    image: postgres:17
    host: 43.199.193.158
    # port: "127.0.0.1:5432:5432" # accessable with ssh tunnel
    env:
      clear:
        PGDATA: "/var/lib/postgresql/17/docker"
      secret:
        - POSTGRES_PASSWORD:DB_PASSWORD
    directories:
      # kamal create a unique directory for each accessory
      # so no need to worry about name collision
      - data:/var/lib/postgresql
