service: openrice-scraper
image: markyiptw/openrice-scraper

servers:
  web:
    - 43.199.193.158
  queue:
    hosts:
      - 43.199.193.158
    cmd: "php /var/www/html/artisan queue:work"
    options:
      health-cmd: "healthcheck-queue"
  task:
    hosts:
      - 43.199.193.158
    cmd: "php /var/www/html/artisan schedule:work"
    options:
      health-cmd: "healthcheck-schedule"

builder:
  arch:
    - arm64

proxy:
  ssl: true
  host: restaurants.himark.tools
  # default is 80
  # but our image listens to 8080
  app_port: 8080
  response_timeout: 120

registry:
  server: localhost:5555

env:
  clear:
    DB_CONNECTION: pgsql
    # hostname inside docker = ${service}-${accessory}
    DB_HOST: openrice-scraper-db
    DB_USERNAME: postgres
    DB_DATABASE: postgres
    AUTORUN_ENABLED: true
    LOG_CHANNEL: stdout
    PHP_OPCACHE_ENABLE: "1"
  secret:
    - APP_KEY
    - DB_PASSWORD
    - POSTHOG_API_KEY
    - VITE_POSTHOG_API_KEY:POSTHOG_API_KEY # shit this is not available at build time

ssh:
  user: ec2-user

volumes:
  - "app_storage:/var/www/html/storage/app"

asset_path: /var/www/html/public/build/assets

accessories:
  db:
    image: postgres:17
    host: 43.199.193.158
    # port: 5432 # this option is for public exposure
    env:
      clear:
        PGDATA: "/var/lib/postgresql/17/docker"
      secret:
        - POSTGRES_PASSWORD:DB_PASSWORD
    directories:
      # kamal create a unique directory for each accessory
      # so no need to worry about name collision
      - data:/var/lib/postgresql
